### PR TITLE
Propose GPLv3

### PR DESCRIPTION
**Pull request by NotAlexNoyle**
Hello,

I maintain a fork of this plugin for my server. I noticed this repository shipped without a license included. I would like to propose adopting the default license for open source Spigot plugins, the GPLv3.

Thank you for your consideration,
- Alex Noyle
TrueOG Founder

Auto-Translated:

Bonjour,

Je maintiens une fourche de ce plugin pour mon serveur. J'ai remarqué ce référentiel expédié sans licence incluse. Je voudrais proposer d'adopter la licence par défaut pour les plugins Spigot open source, le GPLV3.

Merci pour votre considération,
- Alex Noyle
Fondateur de Trueog

### CODE REVIEW

**Comment by YanisBft** [comment]
Hello! Thanks for your pull request.
Indeed, a license is missing, but I would prefer LGPLv3 rather than GPLv3. I let you change that if you wish.
Also, note that this plugin will be refactored in the future to become a gradle project.

**Comment by NotAlexNoyle** [comment]
> Hello! Thanks for your pull request. Indeed, a license is missing, but I would prefer LGPLv3 rather than GPLv3. I let you change that if you wish. Also, note that this plugin will be refactored in the future to become a gradle project.

LGPLv3 is even better. My fork is already using gradle so that's no problem.

**Review by YanisBft — APPROVED** [review]

**Comment by YanisBft** [comment]
Thanks!

**Comment by NotAlexNoyle** [comment]
Feel free to adapt my gradle config: https://github.com/NotAlexNoyle/FirstPlayed-OG/

**Pull request merged**
